# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

# Validates order placement, including cart checkout, shipping details, purchased items, and product references.
mutation PlaceOrder($input: PlaceOrderInput!) {
  placeOrder(input: $input) {
    orderId
    shippingTrackingId
    shippingCost {
      currencyCode
      units
      nanos
    }
    shippingAddress {
      streetAddress
      city
      state
      country
      zipCode
    }
    items {
      productId
      quantity
      cost {
        currencyCode
        units
        nanos
      }
      product {
        id
        name
        picture
        priceUsd {
          currencyCode
          units
          nanos
        }
      }
    }
  }
}
