# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

# Teste l'intégration des reviews et commentaire IA directement en interrogeant la fiche d'un produit
query ProductDetails($productId: ID!, $question: String!) {
  product(id: $productId) {
    id
    name
    description
    picture
    categories
    priceUsd {
      currencyCode
      units
      nanos
    }
    averageReviewScore
    aiReviewSummary(question: $question)
    reviews {
      username
      score
      description
    }
  }
}